version: '3.3'
services:
  anomaly_detector:
    container_name: anomaly_detector
    build: .
    restart: always
    env_file:
      - ./.env
    ports:
      - "5000:5000"
    command: >
      gunicorn --bind 0.0.0.0:5000 'app:app'
    volumes:
      - .:/anomaly_detector
